#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: cat CLUSTER | $PROGRAM GENE_LIST_FILE
";

my %OPT;
getopts('', \%OPT);

if (@ARGV != 1) {
    print STDERR $USAGE;
    exit 1;
}
my $GENE_FILE = shift @ARGV;

my %GENE = ();
open(GENE_FILE, $GENE_FILE) || die;
while (<GENE_FILE>) {
    chomp;
    my ($gene) = split;
    $GENE{$gene} = 1;
}
close(GENE_FILE);

!@ARGV && -t and die $USAGE;
while (<STDIN>) {
    my ($cluster, $gene) = split;
    if ($GENE{$gene}) {
	print;
    }
}
