#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM
-r: align region only
";

use DomRefine::Read;
use DomRefine::Align;

### Settings ###
my %OPT;
getopts('r', \%OPT);

my $TMP_INPUT = define_tmp_file("$PROGRAM.input");
my $TMP_ALIGNMENT = define_tmp_file("$PROGRAM.alignment");
my $TMP_ALIGNMENT_ERR = define_tmp_file("$PROGRAM.alignment.err");
END {
    remove_tmp_file($TMP_INPUT);
    remove_tmp_file($TMP_ALIGNMENT);
    remove_tmp_file($TMP_ALIGNMENT_ERR);
}

### Main ###
-t and die $USAGE;
save_stdin($TMP_INPUT);

my @gene = ();
aligner($TMP_INPUT, $TMP_ALIGNMENT);

system "cat $TMP_ALIGNMENT";
